version: "3"
services:
  website:
    build:
      context: website
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always
    environment:
      API_URL: ${API_URL}
    networks:
      - frontend
  api:
    build:
      context: api
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: always
    environment:
      DB_PASSWORD: ${DB_PASSWD}
    networks:
      - frontend
      - backend
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: pizze_dalieni
    networks:
      - backend
networks:
  frontend:
    ipam:
      driver: default
  backend:
    ipam:
      driver: default
